### PR TITLE
1️⃣

### PR DESCRIPTION
**Pull request by FrontEndCoffee**
👀

### CODE REVIEW

**Comment by markdingemanse** [comment]
KEKW

**Comment by AvOeffelen** [comment]
🙅

**Comment by markdingemanse** [comment]
image

**Comment by BinaryKitten** [comment]
has this been tested?

I know this seems to be a non-sensible project, but this PR just doesn't work 
proof: https://3v4l.org/mW5HU

**Comment by GeeH** [comment]
I ❤️ the enthusiasm but this sadly doesn't work 😢

**Pull request closed without merging**
